In [2]:
import numpy as np

In [2]:
v1 = np.array([3,2,-3])
v2 = np.array([2])
v3 = np.array([4,3])

In [3]:
# Find a magnitude/length of the vector
# linalg it is a sublibrary in numpy
print(np.linalg.norm(v1))
print(np.linalg.norm(v2))
print(np.linalg.norm(v3))

4.69041575982343
2.0
5.0


In [19]:
# The inverse of a square matrix, if one exists, can be found using np.linalg.inv():
M1 = np.array([[2,5],[3,1]])
print(np.linalg.inv(M1))

[[-0.07692308  0.38461538]
 [ 0.23076923 -0.15384615]]


In [24]:
# Solving for unknown variables in a system on linear equations in Ax=b form using 
# np.linalg.solve(), which takes in the A and b parameters.
'''
x + 4y -  z = -1 
-x - 3y + 2z =  2
2x -  y - 2z = -2
'''
# each array in A is an equation from the above system of equations
A = np.array([[1,4,-1],[-1,-3,2],[2,-1,-2]])
# the solution to each equation
b = np.array([-1,2,-2])
# solve for x, y, and z
x,y,z = np.linalg.solve(A,b)

print(x,y,z)

0.0 0.0 1.0


In [22]:
# Represent the following system in NumPy matrix/vector form, then solve for x, y, and z
# Given
'''
4x + z = 2
-y + 2z - 3x = 0
.5y - x - 1.5z = -4
'''

A = np.array([[4,0,1],[-3,-1,2],[-1,.5,-1.5]])
b = np.array([2,0,-4])

x,y,z = np.linalg.solve(A,b)
print(x,y,z)

6.0 -62.0 -22.0


In [6]:
# Gauss-Jordan Elimination Example
A1 = np.array([[1,1,-2],[-1,-1,1],[-2,2,1]])
b1 = np.array([1,2,0])

x,y,z = np.linalg.solve(A1,b1)
print(x,y,z)

-3.25 -1.75 -3.0


In [7]:
# Gauss-Jordan Elimination Inverse Matrices
M = np.array([[0,2,1],[-1,-2,0],[-1,1,2]])
inverse = np.linalg.inv(M)

print(inverse)

[[-4. -3.  2.]
 [ 2.  1. -1.]
 [-3. -2.  2.]]
