In [1]:
import numpy as np

In [14]:
# Two matrices 3x3
m1 = np.array([[1,2,3], [2,3,4], [5,6,7]])
m2 = np.array([[2,2,2],[-1,-1,-1],[0,0,0]])
m3 = np.array([[2,3],[1,1]])
m4 = np.array([[1,1],[5,5]])

# Two vectors
v1 = np.array([1,2,3,4,5])
v2 = np.array([0,0,1,1,1])
v3 = np.array([3,2,1,-3,-1])


In [15]:
M = np.row_stack((v1,v2,v3))
N = np.column_stack((v1,v2,v3))
N.shape

(5, 3)

In [23]:
print(m3*m4)
print('---------')

print(m3@m4)
print(np.matmul(m3,m4))
print('---------')
print('---------')

print(m4@m3)
print(np.matmul(m4,m3))

[[2 3]
 [5 5]]
---------
[[17 17]
 [ 6  6]]
[[17 17]
 [ 6  6]]
---------
---------
[[1 1]
 [5 5]]
[[2 3]
 [1 1]]
[[ 3  4]
 [15 20]]
[[ 3  4]
 [15 20]]


In [4]:
# Subtracting each values in matrices and in vectors
vector1 = np.array([1,3,5,99,100])
matrix1 = np.array([[3,100,3],[1,2,3]])
subtr = 255

print(vector1 - subtr)
print(matrix1 - subtr)
print(np.subtract(matrix1,subtr))

[-254 -252 -250 -156 -155]
[[-252 -155 -252]
 [-254 -253 -252]]
[[-252 -155 -252]
 [-254 -253 -252]]


In [6]:
# 

v1 = np.array([3,-1,2])
v2 = np.array([0,-1,1])

v1_norm = v1 / np.linalg.norm(v1)
v2_norm = v2 / np.linalg.norm(v2)

dot_product = np.dot(v1_norm,v2_norm)
radians = np.arccos(dot_product)
print(radians)

print(np.degrees(radians))

0.9680017740426318
55.46241621381917
