In [1]:
import numpy as np

In [2]:
# Quiz 1:
# What is the angle, in degrees rounded to the nearest whole number, between the following two vectors?

v1 = np.array([3,-1,2])
v2 = np.array([0,-1,1])

v1_norm = v1 / np.linalg.norm(v1)
v2_norm = v2 / np.linalg.norm(v2)

dot_product = np.dot(v1_norm,v2_norm)
radians = np.arccos(dot_product)
print(radians)

print(np.degrees(radians))

0.9680017740426318
55.46241621381917


In [5]:
# Quiz 2 (unsolved)
# What is the expected shape of the solution to the following expression?
# m1 is 4x3
m1 = np.array([[2,3,4],[-2,-2,-2],[0,1,0],[-1,-3,-2]])
# m2 is 3x3
m2 = np.array([[-1,-2,-1],[2,1,-2],[3,0,-3]])
# m3 is 3x1
m3 = np.array([1,2,3])

m2m3 = m2@m3
print("Mult m2&m3: ",m2m3)

m1_m2m3 = m1@m2m3
print("Mult m1&m2m3:", m1_m2m3)



Mult m2&m3:  [-8 -2 -6]
Mult m1&m2m3: [-46  32  -2  26]
[-46  32  -2  26]


In [9]:
# Quiz 3 (Unsolved)
# Use matrix multiplication to find the product of the following two matrix
m1 = np.array([[2,-3,1],[-2,-1,4],[0,2,2]])
m2 = np.array([[3,-2,1],[1,-1,2],[-2,2,0]])

dotm1m2 = np.dot(m1,m2)
print(dotm1m2)

[[  1   1  -4]
 [-15  13  -4]
 [ -2   2   4]]


In [10]:
# Quiz 4 (unsolved)
# Solve the following system of equations using Gaussian elimination
'''
2x-3y+z=2
3x+y+z=-1
-x-2y-z=1
'''
A = np.array([[2,-3,1],[3,1,1],[-1,-2,-1]])
M2 = np.array([3,1,1])
M3 = np.array([-1,-2,-1])

b = np.array([2,-1,1])
x,y,z = np.linalg.solve(A,b)
print(x,y,z)

-0.3333333333333333 -0.6666666666666666 0.6666666666666665


In [11]:
# Quiz 5 (solved)
# What is the solution to the following expression?
'''
5*[3,-2,2] - 2*[1,2,-2]
'''
q = np.array([3,-2,2])
w = np.array([1,2,-2])

solution = 5*q - 2*w
print(solution)

[ 13 -14  14]
