In [1]:
import numpy as np

In [2]:
# Identity matrices 3x3 and 4x4
idM1 = np.eye(3)
idM2 = np.eye(4)

# Zeros matrices 3x3 and 5x3
zeros1 = np.zeros((3,3))
zeros2 = np.zeros((5,3))

m1 = np.array([[1,2,3],[2,1,1],[3,1,9]])
m2 = np.array([[1,6,3],[3,3,3],[4,-1,9]])

In [7]:
# .T attribute or .transpose() 
print(m2.transpose())
print(m2)
print(m2.T)

[[ 1  3  4]
 [ 6  3 -1]
 [ 3  3  9]]
[[ 1  6  3]
 [ 3  3  3]
 [ 4 -1  9]]
[[ 1  3  4]
 [ 6  3 -1]
 [ 3  3  9]]
