In [2]:
import numpy as np

In [19]:
# Vectors
vector1 = np.array([3,-3,2,1])
vector2 = np.array([0,1,1,1,1,1])

# 2D-Metrices
matrix1 = np.array([[2,3,4],[4,5,6]])
matrix2 = np.array([[0,0,0],[1,1,1],[2,2,2]])

# Vectors for combining together into matrices
a = np.array([1,1,1,1])
b = np.array([2,2,2,2])
c = np.array([-1,-1,8,-1])

A = np.column_stack((a,b,c))
B = np.row_stack((a,b,c))

In [24]:
# Using .shape attribute
print(A.shape)
print('--------------')
print(A)

# Index the array with []
print(A[2,2])

# Subset or entire dimension with [:]
print(A[2:,])
print('--------------')
print(A[3:,1:])

# Two ways of viewing columns
# First option is printed out in a row-format (horizontal)
# Second option is printed out in a column-format (vertical)
print(A[:,2])
print('--------------')
print(A[:,2:])

(4, 3)
--------------
[[ 1  2 -1]
 [ 1  2 -1]
 [ 1  2  8]
 [ 1  2 -1]]
8
[[ 1  2  8]
 [ 1  2 -1]]
--------------
[[ 2 -1]]
[-1 -1  8 -1]
--------------
[[-1]
 [-1]
 [ 8]
 [-1]]
