In [1]:
import numpy as np

In [2]:
# Given
# 2 x 3 matrix
A = np.array([[2,3,-4], [-2, 1, -3]])
# 2 x 3 matrix
B = np.array([[1,-1,4], [3,-3,3]])
# 3 x 2 matrix
C = np.array([[1, 2], [3, 4], [5, 6]])

In [4]:
# Matrices multiplication
print(A*B)
print('------------')

# Multiplication by scalar
print(C*3)
print(np.dot(C,3)) # The same output
print('------------')

# Adding two matrices: they should be equally sized
print(A+B)
print('------------')

# Vector dot products
print(np.dot(A,C))
print('------------')

# Multiplication is computed using either the np.matmul() function
# or using @ symbol as shorthand
# Using symbol * will result in an elementwise multiplication instead
print(A@C)
print('------------')
print(np.matmul(A,C))
print('------------')



[[  2  -3 -16]
 [ -6  -3  -9]]
------------
[[ 3  6]
 [ 9 12]
 [15 18]]
[[ 3  6]
 [ 9 12]
 [15 18]]
------------
[[ 3  2  0]
 [ 1 -2  0]]
------------
[[ -9  -8]
 [-14 -18]]
------------
[[ -9  -8]
 [-14 -18]]
------------
[[ -9  -8]
 [-14 -18]]
------------


In [24]:
# Calculate D = 4A - 2B
D = 4*A - 2*B
print(D)
print('------------')


# Calculate E = AC
E = np.matmul(A,C)
print(E)
print(E.shape)
print('------------')

# Calculate F = CA
F = C@A
print(F)
print(F.shape)
print('------------')

# Calculate G = AC
# Check the difference between F and G
G = A@C
print(G)
print(G.shape)

[[  6  14 -24]
 [-14  10 -18]]
------------
[[ -9  -8]
 [-14 -18]]
(2, 2)
------------
[[ -2   5 -10]
 [ -2  13 -24]
 [ -2  21 -38]]
(3, 3)
------------
[[ -9  -8]
 [-14 -18]]
(2, 2)
